### ISSUE TITLE
Homework by 9/3

### ISSUE THREAD

**Issue by ayakomachi** [ayakomachi/ayakomachi#2]
- [x] create a new project board with basic kanban template 
- [x] add this issue to the project board
- [x] add to a blockers column to the project board
- [x] make one note on the project board

@pnsk @domofactor

**Comment by ayakomachi** [comment]
Completed my homework before the deadline!!

**Comment by pnsk** [comment]
Excellent ✨ すごーい ❤️ 

I'd suggest changing a profile image of your account 😄  cc/ @domofactor.
